"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { CalendarDays, FileText, LayoutDashboard, LogOut, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type View = "inicio" | "agenda" | "facturacion" | "clientes";
type Visit = { id: string; scheduled_for: string; status: string; installations: { name: string; address: string; clients: { legal_name: string } } | null };
type Invoice = { id: string; number: string | null; status: string; total: number; issued_on: string | null; clients: { legal_name: string } | null };
type Client = { id: string; legal_name: string; payment_method: string | null; installations: { id: string }[] };
const money = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
const titles: Record<View, string> = { inicio: "Resumen operativo", agenda: "Agenda de visitas", facturacion: "Facturación y cobros", clientes: "Clientes e instalaciones" };

export function DemoApp({ view }: { view: View }) {
  const [ready, setReady] = useState(false); const [signedIn, setSignedIn] = useState(false); const [visits, setVisits] = useState<Visit[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [clients, setClients] = useState<Client[]>([]); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const s = createClient(); const [v, i, c] = await Promise.all([s.from("visits").select("id,scheduled_for,status,installations(name,address,clients(legal_name))").order("scheduled_for"), s.from("invoices").select("id,number,status,total,issued_on,clients(legal_name)").order("created_at", { ascending: false }), s.from("clients").select("id,legal_name,payment_method,installations(id)").order("legal_name")]); const error = v.error || i.error || c.error; if (error) { setMessage(error.message); return; } setVisits((v.data ?? []) as unknown as Visit[]); setInvoices((i.data ?? []) as unknown as Invoice[]); setClients((c.data ?? []) as unknown as Client[]); }, []);
  useEffect(() => { const s = createClient(); s.auth.getSession().then(({ data }) => { setSignedIn(Boolean(data.session)); setReady(true); if (data.session) void load(); }); const { data } = s.auth.onAuthStateChange((_event, session) => { setSignedIn(Boolean(session)); if (session) void load(); }); return () => data.subscription.unsubscribe(); }, [load]);
  if (!ready) return <main className="empty-state">Conectando con Supabase…</main>; if (!signedIn) return <AuthScreen />;
  const complete = async (visit: Visit) => { const s = createClient(); const { error } = await s.from("visits").update({ status: "completed" }).eq("id", visit.id); if (!error) await s.from("interventions").upsert({ visit_id: visit.id, started_at: new Date().toISOString(), completed_at: new Date().toISOString(), customer_notice_status: "not_sent" }, { onConflict: "visit_id" }); setMessage(error ? error.message : "Parte cerrado y guardado en Supabase."); await load(); };
  const pay = async (invoice: Invoice) => { const { error } = await createClient().from("invoices").update({ status: "paid", paid_at: new Date().toISOString() }).eq("id", invoice.id); setMessage(error ? error.message : "Factura marcada como cobrada."); await load(); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><Image src="/concepte-blau-logo.png" alt="Concepte Blau" width={450} height={111} priority /></div><nav className="nav"><Nav href="/" label="Resumen" icon={<LayoutDashboard size={18} />} active={view === "inicio"} /><Nav href="/agenda" label="Agenda" icon={<CalendarDays size={18} />} active={view === "agenda"} /><Nav href="/clientes" label="Clientes" icon={<Users size={18} />} active={view === "clientes"} /><Nav href="/facturacion" label="Facturación" icon={<FileText size={18} />} active={view === "facturacion"} /></nav><button className="profile" onClick={() => void createClient().auth.signOut()}><div className="avatar">CB</div><span>Cerrar sesión</span><LogOut size={16} /></button></aside><main className="main"><header className="topbar"><div><span className="eyebrow">Concepte Blau · Supabase</span><h1>{titles[view]}</h1></div></header><div className="content">{message && <p className="toast" role="status">{message}</p>}{view === "inicio" && <Overview visits={visits} invoices={invoices} clients={clients} complete={complete} />}{view === "agenda" && <Agenda visits={visits} complete={complete} />}{view === "facturacion" && <Billing invoices={invoices} pay={pay} />}{view === "clientes" && <Clients clients={clients} />}</div></main></div>;
}
function Nav({ href, label, icon, active }: { href:string; label:string; icon:ReactNode; active:boolean }) { return <Link href={href} aria-current={active ? "page" : undefined}>{icon}<span>{label}</span></Link>; }
function VisitRow({ visit, complete }: { visit:Visit; complete:(v:Visit)=>void }) { const x = visit.installations; return <div className="visit"><div className="time">{new Intl.DateTimeFormat("es-ES", { hour:"2-digit", minute:"2-digit" }).format(new Date(visit.scheduled_for))}</div><div><div className="visit-title">{x?.clients?.legal_name ?? "Cliente"}</div><div className="visit-meta">{x?.name ?? "Instalación"} · {x?.address ?? ""}</div></div>{visit.status === "completed" ? <span className="badge ok">Completada</span> : <button className="badge progress" onClick={() => complete(visit)}>Cerrar parte</button>}</div>; }
function Overview({ visits, invoices, clients, complete }: { visits:Visit[]; invoices:Invoice[]; clients:Client[]; complete:(v:Visit)=>void }) { const due = invoices.filter((i) => i.status !== "paid"); return <><section className="intro"><div><h2>Datos reales, sin hojas de cálculo.</h2><p>Clientes, visitas y facturas se cargan directamente de Supabase.</p></div><Link className="button accent" href="/agenda">Ver agenda</Link></section><section className="stats"><Stat label="Visitas" value={String(visits.length)} foot={`${visits.filter((v) => v.status === "completed").length} completadas`} /><Stat label="Clientes" value={String(clients.length)} foot="Desde la tabla clients" /><Stat label="Facturas pendientes" value={String(due.length)} foot={money.format(due.reduce((n, i) => n + Number(i.total), 0))} /><Stat label="Facturación" value={money.format(invoices.reduce((n, i) => n + Number(i.total), 0))} foot="Desde invoices" /></section><section className="card" style={{ marginTop:18 }}><div className="card-head"><h3>Próximas visitas</h3></div>{visits.map((v) => <VisitRow key={v.id} visit={v} complete={complete} />)}</section></>; }
function Stat({ label,value,foot }:{label:string;value:string;foot:string}) { return <div className="stat"><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-foot">{foot}</div></div>; }
function Agenda({ visits, complete }:{visits:Visit[];complete:(v:Visit)=>void}) { return <><section className="intro"><div><h2>Agenda desde Supabase</h2><p>Tabla <code>visits</code>, unida a instalaciones y clientes.</p></div></section><section className="agenda-list">{visits.map((v) => <VisitRow key={v.id} visit={v} complete={complete} />)}</section></>; }
function Billing({ invoices,pay }:{invoices:Invoice[];pay:(i:Invoice)=>void}) { return <><section className="intro"><div><h2>Facturación persistente</h2><p>Estados e importes desde <code>invoices</code>.</p></div></section><div className="invoice-list">{invoices.map((i) => <div className="invoice" key={i.id}><div><strong>{i.clients?.legal_name ?? "Cliente"}</strong><span>{i.number ?? "Borrador"} · {i.issued_on ?? "Sin emitir"}</span></div><span className="invoice-total">{money.format(Number(i.total))}</span>{i.status === "paid" ? <span className="badge ok">Cobrada</span> : <button className="badge progress" onClick={() => pay(i)}>Marcar cobrada</button>}</div>)}</div></>; }
function Clients({ clients }:{clients:Client[]}) { return <><section className="intro"><div><h2>Clientes reales</h2><p>Consulta <code>clients</code> e <code>installations</code>.</p></div></section><div className="card"><table className="table"><thead><tr><th>Cliente</th><th>Instalaciones</th><th>Cobro</th></tr></thead><tbody>{clients.map((c) => <tr key={c.id}><td><strong>{c.legal_name}</strong></td><td>{c.installations.length}</td><td>{c.payment_method ?? "Sin definir"}</td></tr>)}</tbody></table></div></>; }
function AuthScreen() { const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState<string | null>(null); const submit=async(mode:"signup"|"login")=>{const s=createClient(); const r=mode === "signup" ? await s.auth.signUp({email,password,options:{data:{full_name:name}}}) : await s.auth.signInWithPassword({email,password}); setMessage(r.error?.message ?? (mode === "signup" ? "Cuenta creada. Confirma tu email si se solicita." : "Sesión iniciada."));}; return <main className="empty-state"><section className="card"><h2>Acceso a Concepte Blau</h2><p>La primera cuenta creada recibirá el rol administrador.</p><label className="field"><span>Nombre</span><input value={name} onChange={(e)=>setName(e.target.value)} /></label><label className="field"><span>Email</span><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} /></label><label className="field"><span>Contraseña</span><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} /></label><div className="modal-foot"><button className="button secondary" onClick={()=>void submit("signup")}>Crear cuenta</button><button className="button" onClick={()=>void submit("login")}>Entrar</button></div>{message && <p role="status">{message}</p>}</section></main>; }
